src/chapter6/beans/Message.java
package chapter6.beans;
import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {

    private int id;
    private int userId;
    
    private int messageId;
    private String title;
    private String category;
    private String text;
    
    private Date createdDate;
    private Date updateDate;
    
    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	
	 public int getMessageId() {
		return messageId;
	}
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	
}

src/chapter6/beans/UserComment.java
package chapter6.beans;

import java.util.Date;

public class UserComment {
	private int id;
    private int userId;
    private String account;
    
    private String text;
    private int messageId;
    
    private Date createdDate;
    private Date updatedDate;

    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String[] getSplitedText() {
		return text.split("\n");
	}
	
	public int getMessageId() {
		return messageId;
	}
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}
	
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpDate() {
		return updatedDate;
	}
	public void setUpDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
}

src/chapter6/controller/HomeServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.Branch;
import chapter6.beans.Department;
import chapter6.beans.User;
import chapter6.beans.UserBranchDepartment;
import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.BranchService;
import chapter6.service.CommentService;
import chapter6.service.DepartmentService;
import chapter6.service.MessageService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	String startDate = request.getParameter("startDate");
        String endData = request.getParameter("endData");
        String searchWord = request.getParameter("searchWord");


        List<UserBranchDepartment> users = (List<UserBranchDepartment>) new UserService().select();
    	List<UserMessage> messages = new MessageService().select(startDate, endData, searchWord);
        List<UserComment> comments = new CommentService().select();
		List<Branch> branches = new BranchService().select();
		List<Department> departments = new DepartmentService().select();
		HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");


        request.setAttribute("startDate", startDate);
        request.setAttribute("endData", endData);
        request.setAttribute("searchWord", searchWord);
        request.setAttribute("loginUser", loginUser);
		request.setAttribute("users", users);
		request.setAttribute("branches", branches);
		request.setAttribute("departments", departments);
        request.setAttribute("comments", comments);
        request.setAttribute("messages", messages);
        request.getRequestDispatcher("/home.jsp").forward(request, response);
    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.beans.UserBranchDepartment;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {
    	List<UserBranchDepartment> users = new UserService().select();

        request.setAttribute("users", users);

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String account= request.getParameter("account");
        String password = request.getParameter("password");
        User user = new UserService().select(account, password);

        List<String> errorMessages = new ArrayList<String>();

        if (account == null || account.isEmpty()  ){
            errorMessages.add("アカウントを入力してください");
        }
        if(user == null) {
        	errorMessages.add("アカウントまたはパスワードが間違っています。");
        }
        if (password.isEmpty() || password == null){
            errorMessages.add("パスワードを入力してください");
        }
        if(errorMessages.size() != 0) {
        	request.setAttribute("account", account);
        	request.setAttribute("password", password);
        	request.setAttribute("errorMessages", errorMessages);
        	request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();

        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/ManegementServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.Branch;
import chapter6.beans.Department;
import chapter6.beans.User;
import chapter6.beans.UserBranchDepartment;
import chapter6.service.BranchService;
import chapter6.service.DepartmentService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/manegement" })
public class ManegementServlet extends HttpServlet{
	@Override
	   protected void doGet(HttpServletRequest request, HttpServletResponse response)
	         throws IOException, ServletException {

	        List<UserBranchDepartment> users = new UserService().select();
	        HttpSession session = request.getSession();
	        User loginUser = (User) session.getAttribute("loginUser");
	        List<Branch> branches = new BranchService().select();
			List<Department> departments = new DepartmentService().select();

			request.setAttribute("branches", branches);
			request.setAttribute("departments", departments); 
	        request.setAttribute("loginUser", loginUser);
	        request.setAttribute("users", users);
	        request.getRequestDispatcher("/manegement.jsp").forward(request, response);
	   }
}

src/chapter6/controller/MessagesServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.beans.User;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/message" })
public class MessagesServlet extends HttpServlet {
	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("/message.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        String title = request.getParameter("title");
        String category = request.getParameter("category");
        String text = request.getParameter("text");

        if (!isValid(title, category, text, errorMessages)) {
            session.setAttribute("errorMessages", errorMessages);
            request.setAttribute("title", title);
            request.setAttribute("category", category);
            request.setAttribute("text", text);
            request.getRequestDispatcher("message.jsp").forward(request, response);
            return;
        }

        Message message = new Message();
        message.setTitle(title);
        message.setCategory(category);
        message.setText(text);

        User user = (User) session.getAttribute("loginUser");
        message.setUserId(user.getId());

        new MessageService().insert(message);
        response.sendRedirect("./");
    }

    private boolean isValid(String title, String category, String text, List<String> errorMessages) {

    	if (StringUtils.isEmpty(title) || StringUtils.strip(title).isEmpty()) {
        	errorMessages.add("件名を入力してください");
        } else if (30 < title.length()) {
        	errorMessages.add("件名は30文字以内で入力してください");
        }
    	if (StringUtils.isEmpty(category) || StringUtils.strip(category).isEmpty()) {
        	errorMessages.add("カテゴリーを入力してください");
        } else if (10 < category.length()) {
        	errorMessages.add("カテゴリーは10文字以内で入力してください");
        }
        if (StringUtils.isEmpty(text)) {
            errorMessages.add("本文を入力してください");
        } else if (1000 < text.length()) {
        	errorMessages.add("本文は1000文字以下で入力してください");
        } else if(text.replace("　"," ").replace(" ","").isEmpty()) {
        	errorMessages.add("本文を入力してください。");
        }
        if (errorMessages.size() != 0) {

            return false;
        }
        return true;
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Branch;
import chapter6.beans.Department;
import chapter6.beans.User;
import chapter6.service.BranchService;
import chapter6.service.DepartmentService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = {"/setting"})
public class SettingServlet extends HttpServlet{

		@Override
		protected void doGet(HttpServletRequest request,HttpServletResponse response)
				throws IOException,ServletException{

			User user = null;
			List<String> errorMessages = new ArrayList<String>();
			HttpSession session = ((HttpServletRequest) request).getSession();

			String urlNumber = request.getParameter("userId");
			if(urlNumber.matches("[0-9]{1,6}") && !(urlNumber.isEmpty())){
				int userId = Integer.valueOf(urlNumber);
				user = new UserService().select(userId);
			}
			if(user == null) {
				errorMessages.add("不正なパラメータが入力されました");
			}
			if(errorMessages.size() != 0) {
				session.setAttribute("errorMessages", errorMessages);
				request.setAttribute("user", user);
				response.sendRedirect("./manegement");
				return;
			}

			List<Branch> branches = new BranchService().select();
			List<Department> departments = new DepartmentService().select();
			String branchName = request.getParameter("branchName");
			String departmentName  = request.getParameter("departmentName");

			request.setAttribute("branchName", branchName);
			request.setAttribute("departmentName", departmentName);
			request.setAttribute("user", user);
			request.setAttribute("branches", branches);
			request.setAttribute("departments", departments);

			request.getRequestDispatcher("setting.jsp").forward(request, response);
		}

		@Override
		protected void doPost(HttpServletRequest request,HttpServletResponse response)
		        throws IOException,ServletException{

			List<String> errorMessages = new ArrayList<String>();
			List<Branch> branches = new BranchService().select();
			List<Department> departments = new DepartmentService().select();

			User user = getUser(request);
			if (!isValid(user, errorMessages)) {

				request.setAttribute("branches", branches);
				request.setAttribute("departments", departments);
				request.setAttribute("errorMessages", errorMessages);
				request.setAttribute("user", user);
				request.getRequestDispatcher("setting.jsp").forward(request, response);
				return;
			}

			new UserService().update(user);

			response.sendRedirect("./");
		}
		private User getUser(HttpServletRequest request) throws IOException, ServletException {
			User user = new User();
			user.setId(Integer.valueOf(request.getParameter("userId")));
			user.setAccount(request.getParameter("account"));
			user.setPassword(request.getParameter("password"));
			user.setCheckPassword(request.getParameter("checkPassword"));
			user.setName(request.getParameter("name"));
			user.setBranchId(Integer.valueOf(request.getParameter("branchId")));
			user.setDepartmentId(Integer.valueOf(request.getParameter("departmentId")));
			return user;
		}
		private boolean isValid(User user, List<String> errorMessages) {
			String account = user.getAccount();
			String password = user.getPassword();
			String checkPassword = user.getCheckPassword();
			String name = user.getName();
			int branchId = user.getBranchId();
			int departmentId = user.getDepartmentId();

			User duplicateAccount = new UserService().duplicateAccount(account);

			if(StringUtils.isEmpty(account)) {
				errorMessages.add("アカウント名を入力してください");
			}
			if(!(account.matches("[azAZ0*9]") || account.length() > 6)) {
				errorMessages.add("アカウント名は６文字以上で入力してください");
			}else if(!(account.matches("[azAZ0*9]") || account.length() < 20)) {
				errorMessages.add("アカウント名は２０文字以下で入力してください");
			}
			if(duplicateAccount != null && duplicateAccount.getId() != user.getId()) {
				errorMessages.add("アカウントが重複しています。");
			}
			if(!(password.equals(checkPassword))) {
				errorMessages.add("確認用とパスワードが違います");
			}
			if(StringUtils.isEmpty(name)) {
				errorMessages.add("ユーザー名を入力してください");
			}
			if(!(StringUtils.isEmpty(name)) && (10 < name.length())) {
				errorMessages.add("ユーザー名は10文字以下で入力してください");
			}
			if(branchId == 1 && departmentId >= 3) {
				errorMessages.add("支社と部署の組み合わせが違います。");
			} else if(branchId == 2 && departmentId <= 2) {
				errorMessages.add("支社と部署の組み合わせが違います。");
			} else if(branchId == 3 && departmentId <= 2) {
				errorMessages.add("支社と部署の組み合わせが違います。");
			} else if(branchId == 4 && departmentId <= 2) {
				errorMessages.add("支社と部署の組み合わせが違います。");
			}
			if(errorMessages.size() != 0) {
				return false;
			}
			return true;
		}

}

WebContent/home.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>掲示板</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="mainContent">
			<div class="link">
				<a href="message">新規投稿</a>
					<c:if test="${loginUser.branchId == 1}">
        				<a href="manegement">ユーザー管理</a>
        			</c:if>
        		<a href="logout">ログアウト</a><br/>
			</div>
        	<c:if test="${not empty errorMessages}">
    	        <div class="errorMessages">
       				<ul class="validate">
           				<c:forEach items="${errorMessages}" var="errorMessage">
               				<li><c:out value="${errorMessage}" />
           				</c:forEach>
        			</ul>
    			</div>
   				<c:remove var="errorMessages" scope="session" />
		   	</c:if>

			<form  action="home" method="get" class="dateCategory">
				日付
				<input type="date" name="startDate" value="${startDate}"><br>
				~
				<input type="date" name="endData" value="${endData}"><br>
				カテゴリ
				<input type="text" name="searchWord" value="${searchWord}"><br>
				<input type="submit" value="絞り込み">
			</form>

			<div class="messages">
    			<c:forEach items="${messages}" var="message">
        			<div class="message">

                			<span class="account"><c:out value="${message.account}" /></span><br><br>

                			<label for="title">タイトル：</label>
                			<span class="title"><c:out value="${message.title}" /></span><br><br>

                			<label for="category">カテゴリー：</label>
                			<span class="category"><c:out value="${message.category}" /></span><br><br>

							<label for="text">投稿内容：</label><br>
                			<c:forEach var="s" items="${message.splitedText}">
            					<div class="text"><c:out value="${s}" /></div>
            				</c:forEach>

							<br><br>
            				<div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>

            		
            			<c:if test="${loginUser.id == message.userId}">
            				<form action="deleteMessage" method="post" onsubmit="return check()">
            					<input type="hidden" name="messageId" value=${message.id}><br />
            					<input type="submit" value="メッセージ削除">
            				</form>
            			</c:if>
            		</div>
            		<script>
						function check(){
						    var result = window.confirm('このコメントを削除します。よろしいですか？');

						    if( result == false ) {
						 		return false;
						    }
						}
					</script>
            		<div class="comment">
        				<c:forEach items="${comments}" var="comment">
        				    <c:set var="id" value="${message.id}"></c:set>
        				   	<c:if test="${id == comment.messageId}">
                				<span class="account"><c:out value="${comment.account}" /></span><br>

                				<c:forEach var="s" items="${comment.splitedText}">
            						<div class="text"><c:out value="${s}" /></div>
            					</c:forEach>

								<br>
            					<div class="date"><fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div><br>

            					<c:if test="${loginUser.id == comment.userId }">
            						<form action="deleteComment" method="post" onsubmit="return commentCheck()">
           			     				<input type="hidden" name="commentId" value=${comment.id}><br />
           								<input type="submit" value="コメント削除">
            						</form>
            					</c:if>
            				</c:if>
        			     </c:forEach>
        			</div>
        			<script>
						function commentCheck(){
						    var result = window.confirm('このコメントを削除します。よろしいですか？');

						    if( result == false ) {
						 		return false;
						    }
						}
					</script>
        				<form action="comments" method="post">
        			   		コメント<br />
        			   		<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
           					<input type="hidden" name="messageId" value="${message.id}"><br />
           					<input type="submit" value="つぶやく">
       				</form>
    			 </c:forEach>
    			 <div>Copyright(c)suzuki_hidenori</div>
			 </div>
			
        </div>
    </body> 
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
    <body>
        <div class="main-contents">
        	<div class="errorMessage">
            	<c:if test="${ not empty errorMessages}">
    		   		<div class="errorMessages">
        				<ul class="validate">
            				<c:forEach items="${errorMessages}" var="errorMessage">
               					<li><c:out value="${errorMessage}" />
            				</c:forEach>
        				</ul>
    				</div>
   					<c:remove var="errorMessages" scope="session" />
				</c:if>
			</div>

            <form action="login" method="post" class="login-form"><br />

				<div class="account-form">
               		<label for="account">アカウント名かメールアドレス</label>
              		<input name="account" id="account" value="${account}"/> <br />
				</div>
				<div class="password-form">
               		<label for="password">パスワード</label>
               		<input name="password" type="password" id="password" value="${password}"/> <br />
				</div>
                <input type="submit" value="ログイン" class="submit-btn"/> <br />
                <div class="copyright">Copyright(c)suzuki_hidenori</div>
            </form>


        </div>
    </body>
</html>

WebContent/manegement.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<link href="./css/style.css" rel="stylesheet" type="text/css">
	<title>ユーザー管理画面</title>
</head>
	<body>
		<c:if test="${ not empty errorMessages }">
    		<div class="errorMessages">
        		<ul>
           			<c:forEach items="${errorMessages}" var="errorMessage">
            			<li><c:out value="${errorMessage}" />
           			</c:forEach>
       			</ul>
   			</div>
   			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<div class="mainContent">

			<div class="link">
				<a href="./">ホーム</a>
        		<a href="signup">ユーザー新規登録</a>
			</div>
			<div class="managementUser">
				<c:forEach items="${users}" var="user">
            		<div class="account-name">
              		  	<div class="account"><c:out value="${user.account}"></c:out></div>
            			<div class="name"><c:out value="${user.name}"></c:out></div>
             	 		<div class="branchId"><c:out value="${user.branchName}"></c:out></div>
            			<div class="departmentId"><c:out value="${user.departmentName}"></c:out></div>
             	 		<c:if test="${user.isStopped == 1}">
             	 			<div class="isStopped"><c:out value="停止中"></c:out></div>
           		   		</c:if>
             	 		<c:if test="${user.isStopped == 0}">
            	  			<div class="isStopped"><c:out value="復活"></c:out></div>
            	  		</c:if>

        			<form action="setting" method="get">
        				<input type="hidden" name="userId" value="${user.id}">
        				<input type="hidden" name="branchName" value="${user.branchName}">
        				<input type="hidden" name="departmentName" value="${user.departmentName}">
          		 		<input type="submit" value="編集">
         		   	</form>

					<c:if test="${loginUser.id != user.id}">
            			<form action="stop" method="post" onsubmit="return outage()" class="stopNumber">
            				<c:if test="${user.isStopped == 0}">
            					<input type="hidden" name="stopNumber" value="1">
            					<input type="hidden" name="userId" value= "${user.id}">
            					<input type="submit" value="停止" formaction="stop">
            				</c:if>
          		  		</form>
          	  			<form action="stop" method="post" onsubmit="return resurrection()">
							<c:if test="${user.isStopped == 1}">
								<input type="hidden" name="stopNumber" value="0">
								<input type="hidden" name="userId" value="${user.id}">
								<input type="submit" value="復活" formaction="stop">
							</c:if>
						</form>
					</c:if>
					</div>
					<script>
						function outage(){
							var result = window.confirm('このユーザーを停止しますか？');
				    		if( result == false ){
				 				return false;
							}
						}
						function resurrection(){
							var result = window.confirm('このユーザーを復活しますか？');
				    		if( result == false ){
				 				return false;
							}
						}
					</script>

    	   		</c:forEach>
     	  	</div>
       	</div>
		<div>Copyright(c)suzuki_hidenori</div>
    </body>
</html>

WebContent/message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>Insert title here</title>
</head>
	<body>
		<c:if test="${not empty errorMessages}">
    		 <div class="errorMessages">
       			<ul class="validate">
            		<c:forEach items="${errorMessages}" var="errorMessage">
             			<li><c:out value="${errorMessage}" />
            		</c:forEach>
        		</ul>
   			</div>
   			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<div class="form-area" >

        	<form action="message" method="post" class="messageForm">
        		<a href ="./">ホーム</a><br/>

 				<label for="title">件名</label>
            	<input name="title" id="title" value="${title}" /><br /><br/>

        		<label for="category">カテゴリ</label>
            	<input name="category" id="category" value="${category}" /><br /><br/>

           		投稿内容<br />
            	<textarea name="text" cols="100" rows="5" class="text-box">${text}</textarea><br />
            	<input type="submit" value="投稿">

				<div class="copyright">Copyright(c)suzuki_hidenori</div>
        	</form>
	 	</div>

	</body>
</html>